version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    env_file: .env
    ports:
      - ${LANCACHE_IP}:80:80/tcp
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    env_file: .env
  dns:
    image: steamcache/steamcache-dns:latest
    env_file: .env
    ports:
      - ${DNS_IP}:53:53/udp
  sniproxy:
    image: steamcache/sniproxy:latest
    env_file: .env
    ports:
      - 443:443/tcp
#  riot:
#    image: steamcache/generic:latest
#    env_file: .env
#    volumes:
#      - ${CACHE_ROOT}/riot/cache:/data/cache
#      - ${CACHE_ROOT}/riot/logs:/data/logs
#    environment:
#      - VIRTUAL_HOST=l3cdn.riotgames.com,worldwide.l3cdn.riotgames.com,riotgamespatcher-a.akamaihd.net,riotgamespatcher-a.akamaihd.net.edgesuite.net
  steam:
    image: steamcache/${STEAMCACHE_CONTAINER}:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/steam/cache:/data/cache
      - ${CACHE_ROOT}/steam/logs:/data/logs
    environment:
      - VIRTUAL_HOST=*.content.steampowered.com,content1.steampowered.com,content2.steampowered.com,content3.steampowered.com,content4.steampowered.com,content5.steampowered.com,content6.steampowered.com,content7.steampowered.com,content8.steampowered.com,cs.steampowered.com,steamcontent.com,client-download.steampowered.com,*.hsar.steampowered.com.edgesuite.net,*.akamai.steamstatic.com,content-origin.steampowered.com,clientconfig.akamai.steamtransparent.com,steampipe.akamaized.net,edgecast.steamstatic.com,steam.apac.qtlglb.com.mwcloudcdn.com,*.cs.steampowered.com,*.edgecast.steamstatic.com,*.steamcontent.com,cdn1-sea1.valve.net,cdn2-sea1.valve.net,*.steam-content-dnld-1.apac-1-cdn.cqloud.com,steam.apac.qtlglb.com,edge.steam-dns.top.comcast.net,edge.steam-dns-2.top.comcast.net,steamcdn-a.akamaihd.net

#  blizzard:
#    image: steamcache/generic:latest
#    env_file: .env
#    volumes:
#      - ${CACHE_ROOT}/blizzard/cache:/data/cache
#      - ${CACHE_ROOT}/blizzard/logs:/data/logs
#    environment:
#      - VIRTUAL_HOST=dist.blizzard.com,dist.blizzard.com.edgesuite.net,llnw.blizzard.com,edgecast.blizzard.com,blizzard.vo.llnwd.net,blzddist1-a.akamaihd.net,blzddist2-a.akamaihd.net,blzddist3-a.akamaihd.net,blzddist4-a.akamaihd.net,level3.blizzard.com,nydus.battle.net,edge.blizzard.top.comcast.net